name: prac_res
description: "A Visual Novel Editor!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # Local Drift for bug testing.
  # drift:
  #   path: "C:/Users/Elijah Ang/Desktop/Projects/Coding/Flutter/drift/drift"
  # drift_flutter:
  #   path: "C:/Users/Elijah Ang/Desktop/Projects/Coding/Flutter/drift/drift_flutter"

  # Drift for database functionality.
  drift: ^2.28.2
  drift_flutter: ^0.2.8

  # Used for demangling Drift stack trace output.
  stack_trace: ^1.12.1

  # For file selection functionality. Also I wrote this library!
  junction: 
    path: "C:/Users/Elijah Ang/Desktop/Projects/Coding/Dart/junction"

  # Riverpod-esque packages for global & local state management
  flutter_riverpod: ^3.3.1
  flutter_hooks: ^0.21.3+1

  # Used for UI elements
  device_frame: ^1.4.0
  animated_text_kit: ^4.3.0
  # flutter_resizable_container: ^4.2.0

  # Used for its [intersperse] function on iterables. Also I wrote this library!
  handy: ^1.1.6

  # Used for resolver scripts.
  dart_eval: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Used for Drift codegen
  build_runner: ^2.4.0
  drift_dev: ^2.28.2

  # drift_dev:
  #   path: "C:/Users/Elijah Ang/Desktop/Projects/Coding/Flutter/drift/drift_dev"

flutter:
  uses-material-design: true