// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'dart:typed_data' as i2;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    scenes,
    sceneParts,
    places,
    backgroundMetadatas,
    frames,
    scenePartResolvers,
    customSceneParts,
    sceneTimelineView,
    actors,
    poseMetadatas,
    framePoses,
    framePosesView,
    choices,
    frameChoices,
    frameChoicesView,
    backgroundImages,
    poseImages,
    choiceOptions,
    resolverChoiceReference,
    resolverScenePartReference,
    dialogueBoxes,
    oneSelectedPerChoice,
  ];
  late final Shape0 scenes = Shape0(
    source: i0.VersionedTable(
      entityName: 'scenes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 sceneParts = Shape1(
    source: i0.VersionedTable(
      entityName: 'scene_parts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 places = Shape0(
    source: i0.VersionedTable(
      entityName: 'places',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 backgroundMetadatas = Shape2(
    source: i0.VersionedTable(
      entityName: 'background_metadatas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_5, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 frames = Shape3(
    source: i0.VersionedTable(
      entityName: 'frames',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scene_part_id)'],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 scenePartResolvers = Shape4(
    source: i0.VersionedTable(
      entityName: 'scene_part_resolvers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scene_part_id)'],
      columns: [_column_6, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 customSceneParts = Shape5(
    source: i0.VersionedTable(
      entityName: 'custom_scene_parts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scene_part_id)'],
      columns: [_column_6, _column_9],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sceneTimelineView = Shape6(
    source: i0.VersionedView(
      entityName: 'scene_timeline_view',
      createViewStmt:
          'CREATE VIEW scene_timeline_view AS SELECT scene_parts.id, scene_parts.scene_id, scene_parts."order", scene_parts.part_type, frames.background_id, scene_part_resolvers.dart_resolver_script, custom_scene_parts.event_id FROM scene_parts LEFT OUTER JOIN frames ON frames.scene_part_id = scene_parts.id LEFT OUTER JOIN scene_part_resolvers ON scene_part_resolvers.scene_part_id = scene_parts.id LEFT OUTER JOIN custom_scene_parts ON custom_scene_parts.scene_part_id = scene_parts.id;',
      columns: [
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 actors = Shape0(
    source: i0.VersionedTable(
      entityName: 'actors',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 poseMetadatas = Shape2(
    source: i0.VersionedTable(
      entityName: 'pose_metadatas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_17, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 framePoses = Shape7(
    source: i0.VersionedTable(
      entityName: 'frame_poses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_18, _column_19, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 framePosesView = Shape8(
    source: i0.VersionedView(
      entityName: 'frame_poses_view',
      createViewStmt:
          'CREATE VIEW frame_poses_view AS SELECT frame_poses.id, frame_poses.frame_scene_part_id, frame_poses.pose_id, frame_poses."order", pose_metadatas.group_id, pose_metadatas.name FROM frame_poses LEFT OUTER JOIN pose_metadatas ON pose_metadatas.id = frame_poses.pose_id;',
      columns: [
        _column_10,
        _column_20,
        _column_21,
        _column_12,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 choices = Shape0(
    source: i0.VersionedTable(
      entityName: 'choices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 frameChoices = Shape9(
    source: i0.VersionedTable(
      entityName: 'frame_choices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(frame_scene_part_id)'],
      columns: [_column_18, _column_24],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 frameChoicesView = Shape10(
    source: i0.VersionedView(
      entityName: 'frame_choices_view',
      createViewStmt:
          'CREATE VIEW frame_choices_view AS SELECT frame_choices.frame_scene_part_id, frame_choices.choice_id, choices.name FROM frame_choices LEFT OUTER JOIN choices ON choices.id = frame_choices.choice_id;',
      columns: [_column_20, _column_25, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 backgroundImages = Shape11(
    source: i0.VersionedTable(
      entityName: 'background_images',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(metadata_id)'],
      columns: [_column_26, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 poseImages = Shape11(
    source: i0.VersionedTable(
      entityName: 'pose_images',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(metadata_id)'],
      columns: [_column_28, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 choiceOptions = Shape12(
    source: i0.VersionedTable(
      entityName: 'choice_options',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 resolverChoiceReference = Shape13(
    source: i0.VersionedTable(
      entityName: 'resolver_choice_reference',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_31, _column_24, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 resolverScenePartReference = Shape14(
    source: i0.VersionedTable(
      entityName: 'resolver_scene_part_reference',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_31, _column_33, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 dialogueBoxes = Shape15(
    source: i0.VersionedTable(
      entityName: 'dialogue_boxes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(frame_scene_part_id)'],
      columns: [_column_18, _column_34, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index oneSelectedPerChoice = i1.Index(
    'one_selected_per_choice',
    'CREATE UNIQUE INDEX IF NOT EXISTS one_selected_per_choice ON choice_options (choice_id) WHERE is_selected = 1',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sceneId =>
      columnsByName['scene_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get order =>
      columnsByName['order']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get partType =>
      columnsByName['part_type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scene_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES scenes(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<double> _column_3(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'order',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'part_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (part_type IN (\'frame\', \'resolver\', \'custom\'))',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'group_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES places(id)ON DELETE CASCADE',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get scenePartId =>
      columnsByName['scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get backgroundId =>
      columnsByName['background_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scene_part_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES scene_parts(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'background_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NULL REFERENCES background_metadatas(id)ON DELETE SET NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get scenePartId =>
      columnsByName['scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dartResolverScript =>
      columnsByName['dart_resolver_script']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dart_resolver_script',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get scenePartId =>
      columnsByName['scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get eventId =>
      columnsByName['event_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'event_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedView {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sceneId =>
      columnsByName['scene_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get order =>
      columnsByName['order']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get partType =>
      columnsByName['part_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get backgroundId =>
      columnsByName['background_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dartResolverScript =>
      columnsByName['dart_resolver_script']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get eventId =>
      columnsByName['event_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scene_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_12(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'order',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'part_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'background_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dart_resolver_script',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'event_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'group_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES actors(id)ON DELETE CASCADE',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get frameScenePartId =>
      columnsByName['frame_scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get poseId =>
      columnsByName['pose_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get order =>
      columnsByName['order']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'frame_scene_part_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES frames(scene_part_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pose_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NULL REFERENCES pose_metadatas(id)ON DELETE SET NULL',
    );

class Shape8 extends i0.VersionedView {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get frameScenePartId =>
      columnsByName['frame_scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get poseId =>
      columnsByName['pose_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get order =>
      columnsByName['order']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'frame_scene_part_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pose_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'group_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get frameScenePartId =>
      columnsByName['frame_scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get choiceId =>
      columnsByName['choice_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'choice_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES choices(id)ON DELETE SET NULL',
    );

class Shape10 extends i0.VersionedView {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get frameScenePartId =>
      columnsByName['frame_scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get choiceId =>
      columnsByName['choice_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'choice_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get metadataId =>
      columnsByName['metadata_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get imageData =>
      columnsByName['image_data']! as i1.GeneratedColumn<i2.Uint8List>;
}

i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'metadata_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES background_metadatas(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<i2.Uint8List> _column_27(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'image_data',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'metadata_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES pose_metadatas(id)ON DELETE CASCADE',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get choiceId =>
      columnsByName['choice_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isSelected =>
      columnsByName['is_selected']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'choice_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES choices(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_selected',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_selected IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get resolverScenePartId =>
      columnsByName['resolver_scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get choiceId =>
      columnsByName['choice_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get identifier =>
      columnsByName['identifier']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_31(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'resolver_scene_part_id',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL REFERENCES scene_part_resolvers(scene_part_id)ON DELETE CASCADE',
);
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get resolverScenePartId =>
      columnsByName['resolver_scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scenePartId =>
      columnsByName['scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get identifier =>
      columnsByName['identifier']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scene_part_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES scene_parts(id)ON DELETE SET NULL',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get frameScenePartId =>
      columnsByName['frame_scene_part_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dialogue =>
      columnsByName['dialogue']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dialogue',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    scenes,
    sceneParts,
    places,
    backgroundMetadatas,
    frames,
    scenePartResolvers,
    customSceneParts,
    sceneTimelineView,
    actors,
    poseMetadatas,
    framePoses,
    framePosesView,
    choices,
    frameChoices,
    frameChoicesView,
    backgroundImages,
    poseImages,
    choiceOptions,
    dialogueBoxes,
    oneSelectedPerChoice,
  ];
  late final Shape0 scenes = Shape0(
    source: i0.VersionedTable(
      entityName: 'scenes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 sceneParts = Shape1(
    source: i0.VersionedTable(
      entityName: 'scene_parts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 places = Shape0(
    source: i0.VersionedTable(
      entityName: 'places',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 backgroundMetadatas = Shape2(
    source: i0.VersionedTable(
      entityName: 'background_metadatas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_5, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 frames = Shape3(
    source: i0.VersionedTable(
      entityName: 'frames',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scene_part_id)'],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 scenePartResolvers = Shape4(
    source: i0.VersionedTable(
      entityName: 'scene_part_resolvers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scene_part_id)'],
      columns: [_column_6, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 customSceneParts = Shape5(
    source: i0.VersionedTable(
      entityName: 'custom_scene_parts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scene_part_id)'],
      columns: [_column_6, _column_9],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sceneTimelineView = Shape6(
    source: i0.VersionedView(
      entityName: 'scene_timeline_view',
      createViewStmt:
          'CREATE VIEW scene_timeline_view AS SELECT scene_parts.id, scene_parts.scene_id, scene_parts."order", scene_parts.part_type, frames.background_id, scene_part_resolvers.dart_resolver_script, custom_scene_parts.event_id FROM scene_parts LEFT OUTER JOIN frames ON frames.scene_part_id = scene_parts.id LEFT OUTER JOIN scene_part_resolvers ON scene_part_resolvers.scene_part_id = scene_parts.id LEFT OUTER JOIN custom_scene_parts ON custom_scene_parts.scene_part_id = scene_parts.id;',
      columns: [
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 actors = Shape0(
    source: i0.VersionedTable(
      entityName: 'actors',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 poseMetadatas = Shape2(
    source: i0.VersionedTable(
      entityName: 'pose_metadatas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_17, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 framePoses = Shape7(
    source: i0.VersionedTable(
      entityName: 'frame_poses',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_18, _column_19, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 framePosesView = Shape8(
    source: i0.VersionedView(
      entityName: 'frame_poses_view',
      createViewStmt:
          'CREATE VIEW frame_poses_view AS SELECT frame_poses.id, frame_poses.frame_scene_part_id, frame_poses.pose_id, frame_poses."order", pose_metadatas.group_id, pose_metadatas.name FROM frame_poses LEFT OUTER JOIN pose_metadatas ON pose_metadatas.id = frame_poses.pose_id;',
      columns: [
        _column_10,
        _column_20,
        _column_21,
        _column_12,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 choices = Shape0(
    source: i0.VersionedTable(
      entityName: 'choices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 frameChoices = Shape9(
    source: i0.VersionedTable(
      entityName: 'frame_choices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(frame_scene_part_id)'],
      columns: [_column_18, _column_24],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 frameChoicesView = Shape10(
    source: i0.VersionedView(
      entityName: 'frame_choices_view',
      createViewStmt:
          'CREATE VIEW frame_choices_view AS SELECT frame_choices.frame_scene_part_id, frame_choices.choice_id, choices.name FROM frame_choices LEFT OUTER JOIN choices ON choices.id = frame_choices.choice_id;',
      columns: [_column_20, _column_25, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 backgroundImages = Shape11(
    source: i0.VersionedTable(
      entityName: 'background_images',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(metadata_id)'],
      columns: [_column_26, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 poseImages = Shape11(
    source: i0.VersionedTable(
      entityName: 'pose_images',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(metadata_id)'],
      columns: [_column_28, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 choiceOptions = Shape12(
    source: i0.VersionedTable(
      entityName: 'choice_options',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 dialogueBoxes = Shape15(
    source: i0.VersionedTable(
      entityName: 'dialogue_boxes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(frame_scene_part_id)'],
      columns: [_column_18, _column_34, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index oneSelectedPerChoice = i1.Index(
    'one_selected_per_choice',
    'CREATE UNIQUE INDEX IF NOT EXISTS one_selected_per_choice ON choice_options (choice_id) WHERE is_selected = 1',
  );
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
